# Generated by Django 4.2.5 on 2023-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0002_trail_trailcrumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailcrumb',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
