# Generated by Django 4.2.5 on 2023-09-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0003_alter_trailcrumb_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trailcrumb',
            unique_together=set(),
        ),
    ]
