# Generated by Django 4.2.5 on 2023-09-18 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crumbs', '0004_alter_trailcrumb_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trail',
            unique_together={('name', 'user'), ('slug', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='trailcrumb',
            unique_together={('trail', 'order')},
        ),
    ]
