# Generated by Django 4.2.5 on 2023-09-18 14:33

import apps.crumbs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0005_alter_trail_unique_together_and_more'),
    ]

    operations = [
    ]
