# Generated by Django 4.2.5 on 2023-09-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0006_alter_trailcrumb_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailcrumb',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
